namespace Device.Polhemus
{
    public enum  PDIePiCommType	
	{
		PI_CNX_NONE = -2
		, PI_CNX_UNKNOWN = -1
		, PI_CNX_USB = 0
		, PI_CNX_SERIAL

	};

    public enum  PDIePiFrameRate
	{
		PI_FRATE_60 = 2
		, PI_FRATE_MIN = 3
		, PI_FRATE_120 = PI_FRATE_MIN
		, PI_FRATE_HALF = PI_FRATE_120
		, PI_FRATE_240 
		, PI_FRATE_NORMAL = PI_FRATE_240
		, PI_FRATE_MAX = PI_FRATE_240
	} ;

    public static class ErrCodeConst
    { 
        public const uint PI_ERROR_BAND_MASK = 0xffff0000;
        public const uint PI_ERROR_LEVEL_MASK = 0x0000f000;
        public const uint PI_ERROR_LEVEL_WARN1 = 0x00001000;
        public const uint PI_HOST_SYS_ERROR_BAND = 0x20010000;
        public const uint PI_HOST_ERROR_BAND = 0x20020000;
        public const uint PI_DEVICE_ERROR_BAND = 0x20040000;
        public const uint PI_API_ERROR_BAND = 0x20080000;
    }

    public enum  PDIePiErrCode:uint
	{
 

		PI_NOERROR=0     // equivalent results, success & noerror
		,
        PI_HOST_SYS_ERROR = ErrCodeConst.PI_HOST_SYS_ERROR_BAND
		, PI_HOST_SYS_CNX_USB_CREATE_ERROR
		, PI_HOST_SYS_CNX_SER_CREATE_ERROR
		, PI_HOST_SYS_CNX_CFG_ERROR
		, PI_HOST_SYS_WRITE_ERROR
		, PI_HOST_SYS_WAIT_WRITE_ERROR
		, PI_HOST_SYS_WAIT_READ_ERROR
		, PI_HOST_SYS_READ_ERROR
		, PI_HOST_SYS_CLOSE_ERROR
		, PI_HOST_SYS_PIPE_CREATE_ERROR
		, PI_HOST_SYS_PIPE_DISC_ERROR
		, PI_HOST_SYS_PIPE_WRITE_ERROR
		, PI_HOST_SYS_CREATE_THREAD_ERROR
		, PI_HOST_SYS_GET_THREAD_STATUS_ERROR
		, PI_HOST_SYS_TERM_THREAD_ERROR
		, PI_HOST_SYS_DEVIO_ERROR

		,
        PI_HOST_ERROR = ErrCodeConst.PI_HOST_ERROR_BAND 
		, PI_HOST_NOCNX_ERROR
		, PI_HOST_BUILD_CMD_ERROR
		, PI_HOST_PARSE_RSP_ERROR
		, PI_HOST_STATE_ERROR
		, PI_HOST_NO_RESP
		, PI_HOST_FRAME_ERROR
		, PI_HOST_ASYNCINPROG_ERROR
		, PI_HOST_OVERFLOW_ERROR
		, PI_HOST_FRAME_IGNORED
		, PI_HOST_SERNUM_NOT_FOUND
		,
        PI_HOST_CONT_CMD_SENT = ErrCodeConst.PI_HOST_ERROR_BAND + 0x1001

		,
        PI_DEVICE_ERROR = ErrCodeConst.PI_DEVICE_ERROR_BAND
		, PI_DEVICE_NOT_DETECTED
		, PI_DEVICE_ERROR_FLAG
		, PI_DEVICE_CMD_FAILED
		, PI_DEVICE_NOT_RECOG
		, PI_DEVICE_NOT_FOUND
		,
        PI_DEVICE_INFO = ErrCodeConst.PI_DEVICE_ERROR_BAND + 0x1001

		,
        PI_API_ERROR = ErrCodeConst.PI_API_ERROR_BAND
		, PI_API_INVALID_ARGS
		, PI_API_CONFIG_ERROR
		, PI_API_NO_HWND_PROVIDED
	};
}
