using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BeautySim.Common
{
    public enum Enum_AnaysisVariablesToCheck
    {
        H_INJECTIONS_ON_FRONTAL_L1_RIGHT,
        H_INJECTIONS_ON_FRONTAL_L1_LEFT,
        H_INJECTIONS_ON_CORRUGATORS_LATERAL_LEFT,
        H_INJECTIONS_ON_CORRUGATORS_LATERAL_RIGHT,
        H_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL_RIGHT,
        H_INJECTIONS_ON_ORBICULAR_LOWER_PROXIMAL_RIGHT,
        H_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL_LEFT,
        H_INJECTIONS_ON_ORBICULAR_LOWER_PROXIMAL_LEFT,
        H_ANGULAR_INJECTION_PROCERUS_TOWARD_LEFT,
        H_ANGULAR_INJECTION_PROCERUS_TOWARD_RIGHT,
        H_ANGULAR_INJECTION_PROCERUS_TOWARD_UP,
        M_ASIMMETRY_INJECTIONS_FRONTAL_RIGHT,
        M_ASIMMETRY_INJECTIONS_FRONTAL_LEFT,
        M_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL_RIGHT,
        M_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL_LEFT,
        O_FRONTAL_RIGHT,
        O_FRONTAL_LEFT,
        O_CORRUGATORS_LEFT,
        O_CORRUGATORS_RIGHT,
        O_PROCERUS,
        O_ORBICULARIS_RIGHT,
        O_ORBICULARIS_LEFT,
        C_FRONTAL_RIGHT,
        C_FRONTAL_LEFT,
        C_CORRUGATORS_LEFT,
        C_CORRUGATORS_RIGHT,
        C_PROCERUS,
        C_ORBICULARIS_RIGHT,
        C_ORBICULARIS_LEFT,

        HH_INJECTIONS_ON_FRONTAL_L1_RIGHT_MAX,
        HH_INJECTIONS_ON_FRONTAL_L1_LEFT_MAX,
        HH_INJECTIONS_ON_CORRUGATORS_LATERAL_LEFT_MAX,
        HH_INJECTIONS_ON_CORRUGATORS_LATERAL_RIGHT_MAX,
        HH_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL_RIGHT_MAX,
        HH_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL_LEFT_MAX,
        MH_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL_RIGHT_MAX,
        MH_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL_LEFT_MAX,

        HB_INJECTIONS_ON_FRONTAL,
        HB_INJECTIONS_ON_CORRUGATORS_LATERAL,
        HB_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL,
        HB_INJECTIONS_ON_ORBICULAR_LOWER_PROXIMAL,
        MB_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL,
        HHB_INJECTIONS_ON_FRONTAL_MAX,
        HHB_INJECTIONS_ON_CORRUGATORS_LATERAL_MAX,
        HHB_INJECTIONS_ON_ORBICULAR_UPPER_PROXIMAL_MAX,
        MHB_EXCESSIVE_INJECTIONS_ON_CORRUGATORS_PROXIMAL_MAX,

        COR_FRONTAL,
        COR_CENTRAL,
        COR_ORBICULAR_LEFT,
        COR_ORBICULAR_RIGHT
    }
}
