using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BeautySim.Common
{
    public enum Enum_PointDefinition
    {
        F_1_C0 = 0,
        F_1_L1,
        F_1_L2,
        F_1_L3,
        F_1_L4,
        F_1_R1,
        F_1_R2,
        F_1_R3,
        F_1_R4,
        F_2_C0,
        F_2_L1,
        F_2_L2,
        F_2_L3,
        F_2_L4,
        F_2_R1,
        F_2_R2,
        F_2_R3,
        F_2_R4,
        F_3_C0,
        F_3_L1,
        F_3_L2,
        F_3_L3,
        F_3_L4,
        F_3_R1,
        F_3_R2,
        F_3_R3,
        F_3_R4,
        F_4_C0,
        F_4_L1,
        F_4_L2,
        F_4_R1,
        F_4_R2,
        F_4_L3,
        F_4_R3,
        P_U0,
        P_L0,
        C_L1,
        C_L2,
        C_L3,
        C_L4,
        C_L5,
        C_R1,
        C_R2,
        C_R3,
        C_R4,
        C_R5,
        E_L1,
        E_R1,
        OR_1_C0,
        OR_1_U1,
        OR_1_U2,
        OR_1_U3,
        OR_1_U4,
        OR_1_L1,
        OR_1_L2,
        OR_1_L3,
        OR_1_L4,
        OR_2_C0,
        OR_2_U1,
        OR_2_U2,
        OR_2_L1,
        OR_2_L2,
        OL_1_C0,
        OL_1_U1,
        OL_1_U2,
        OL_1_U3,
        OL_1_U4,
        OL_1_L1,
        OL_1_L2,
        OL_1_L3,
        OL_1_L4,
        OL_2_C0,
        OL_2_U1,
        OL_2_U2,
        OL_2_L1,
        OL_2_L2,
        RE_EXT,
        LE_EXT,
        RL_CORNER,
        LE_INT,
        LL_CORNER,
        RE_INT,
        NOSEPOINT
    }
}
